# Generated by Django 5.2.1 on 2025-05-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='piece',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
