# Generated by Django 5.2.1 on 2025-05-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
