# Generated by Django 5.2.1 on 2025-06-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firm_file',
            field=models.FileField(blank=True, null=True, upload_to='firm_file'),
        ),
        migrations.AddField(
            model_name='profile',
            name='firm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('erkak', 'erkak'), ('ayol', 'ayol')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('seller', 'seller'), ('client', 'client')], max_length=20, null=True),
        ),
    ]
